var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};
$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}},"es6-impl","es3");$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var e=b.length;for(c=c||0;c<e;c++)if(b[c]==a||Object.is(b[c],a))return!0;return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6-impl","es3");
$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}},"es6-impl","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;
$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");
var Actor=function(a,b,c){this.x=void 0===a?0:a;this.y=void 0===b?0:b;this.z=void 0===c?0:c;this.radius=0;this.spawnList=[]};Actor.prototype.getDistance=function(a){var b=this.x-a.x;a=this.y-a.y;return Math.sqrt(b*b+a*a)};Actor.prototype.getRadian=function(a){return Math.atan2(this.y-a.y,this.x-a.x)};Actor.prototype.getMidpoint=function(a){return new Actor((this.x+a.x)/2,(this.y+a.y)/2)};
Actor.prototype.getInterimPoint=function(a,b,c){var d=this.x-a.x;a=this.y-a.y;b=Math.sqrt(d*d+a*a)*(void 0===b?1:b)/(void 0===c?1:c);d=Math.atan2(a,d);return new Actor(this.x-Math.cos(d)*b,this.y-Math.sin(d)*b)};Actor.prototype.includes=function(a,b,c){a=this.x-a;b=this.y-b;return Math.sqrt(a*a+b*b)<((void 0===c?0:c)|this.radius)};Actor.prototype.isHit=function(a,b){return this.includes(a,b)};Actor.prototype.eject=function(){this.isGone=!0};Actor.prototype.react=function(){return[]};
Actor.prototype.draw=function(a){};$jscomp.global.Object.defineProperties(Actor.prototype,{spawn:{configurable:!0,enumerable:!0,get:function(){var a=this.spawnList;this.spawnList=[];return a}}});var ActorHandle=function(a,b){Actor.call(this,a,b);this.radius=4;this.logicalRadius=2*this.radius;this.prev=this;this.next=this};$jscomp.inherits(ActorHandle,Actor);ActorHandle.prototype.add=function(a){var b=this.next;this.next=a;a.prev=this;a.next=b;b.prev=a};
ActorHandle.prototype.isHit=function(a,b){return this.hit=this.includes(a,b,this.logicalRadius)};
ActorHandle.prototype.isLineHit=function(a,b){if(this.includes(a,b,this.logicalRadius))return!1;for(var c=!1,d=this.nextCp,e=this.next.prevCp,g=this.getDistance(this.next)/this.radius,f=0;f<g;f++){var k=this.getInterimPoint(d,f,g),l=e.getInterimPoint(this.next,f,g),h=d.getInterimPoint(e,f,g),k=k.getInterimPoint(h,f,g),l=h.getInterimPoint(l,f,g),h=k.getInterimPoint(l,f,g),l=h.x-a,h=h.y-b;Math.sqrt(l*l+h*h)<this.radius&&(c=!0)}return c};
ActorHandle.prototype.draw=function(a){this.parent.selected&&(a.save(),a.beginPath(),a.fillStyle=this.hit?"aqua":"gray",a.arc(this.x,this.y,this.radius,0,2*Math.PI,!1),a.fill(),a.restore())};ActorHandle.prototype.drawGuide=function(a){var b=this.prevCp,c=this.nextCp;a.save();a.lineWidth=1;a.strokeStyle="cyan";a.beginPath();a.moveTo(this.x,this.y);a.lineTo(b.x,b.y);a.stroke();a.strokeStyle="lime";a.beginPath();a.moveTo(this.x,this.y);a.lineTo(c.x,c.y);a.stroke();a.restore()};
ActorHandle.prototype.drawSelfCurve=function(a){var b=this.nextCp,c=this.next.prevCp,d=this.getDistance(this.next)/this.radius;a.save();for(var e=0;e<d;e++){var g=this.getInterimPoint(b,e,d),f=c.getInterimPoint(this.next,e,d),k=b.getInterimPoint(c,e,d),g=g.getInterimPoint(k,e,d),f=k.getInterimPoint(f,e,d),f=g.getInterimPoint(f,e,d);a.strokeStyle="pink";a.beginPath();a.arc(f.x,f.y,this.radius,0,2*Math.PI,!1);a.stroke()}a.restore()};
ActorHandle.prototype.drawCurve=function(a){var b=this.nextCp,c=this.next.prevCp;a.beginPath();a.moveTo(this.x,this.y);a.bezierCurveTo(b.x,b.y,c.x,c.y,this.next.x,this.next.y);a.stroke()};
$jscomp.global.Object.defineProperties(ActorHandle.prototype,{list:{configurable:!0,enumerable:!0,get:function(){for(var a=[],b=this.next;b!=this;)a.push(b),b=b.next;return a}},listAll:{configurable:!0,enumerable:!0,get:function(){for(var a=[],b=this.next;;){a.push(b);if(b==this)break;b=b.next}return a}},radian:{configurable:!0,enumerable:!0,get:function(){var a=this.prev,b=this.next;return Math.atan2(b.y-a.y,b.x-a.x)}},prevCp:{configurable:!0,enumerable:!0,get:function(){var a=this.radian,b=.2*this.getDistance(this.prev);
return new Actor(this.x-Math.cos(a)*b,this.y-Math.sin(a)*b)}},nextCp:{configurable:!0,enumerable:!0,get:function(){var a=this.radian,b=.2*this.getDistance(this.next);return new Actor(this.x+Math.cos(a)*b,this.y+Math.sin(a)*b)}}});var Chain=function(a,b){a=void 0===a?null:a;Actor.call(this);this.id=null==a?UUID.toString():a;this.gender=b;this.parents=null;this.partnerList=[];this.childrenMap={}};$jscomp.inherits(Chain,Actor);Chain.prototype.attributeChanged=function(){};
Chain.prototype.listOccupancy=function(a){this.partnerList.forEach(function(a){});return{left:1,right:1}};Chain.prototype.addParents=function(a){a.mother.addPartner(a.father);a.addChild(this);this.parents=a};Chain.prototype.addPartner=function(a){this.partnerList.push(a);a.partnerList.push(this)};Chain.prototype.listRealChildren=function(a){return(a=this.childrenMap[a.id])?a:[]};
Chain.prototype.listChildren=function(a){var b=[];a=this.childrenMap[a.id];if(!a)return b;a.forEach(function(a){var c=a.partnerList;a.isMale?(b.push(a),b=b.concat(c)):(b=b.concat(c),b.push(a))});return b};Chain.prototype.remove=function(){this.parents&&this.parents.removeChild(this);this.eject()};
$jscomp.global.Object.defineProperties(Chain.prototype,{gender:{configurable:!0,enumerable:!0,get:function(){return this._gender},set:function(a){this._gender=a;this.attributeChanged()}},isMale:{configurable:!0,enumerable:!0,get:function(){return"m"==this.gender}},mother:{configurable:!0,enumerable:!0,get:function(){return this.parents?this.parents.mother:null}},father:{configurable:!0,enumerable:!0,get:function(){return this.parents?this.parents.father:null}},numOfPartner:{configurable:!0,enumerable:!0,
get:function(){return this.partnerList.length}},hasChild:{configurable:!0,enumerable:!0,get:function(){if(!this.isMale)return 0<Object.keys(this.childrenMap).length;var a=!1;this.partnerList.forEach(function(b){b.hasChild&&(a=!0)});return a}}});var Controller=function(a){this.keys={};this.point={};this.touch=!1;this.init(void 0===a?!1:a);Controller.Instance=this};Controller.prototype.init=function(a){a||window.addEventListener("contextmenu",function(a){a.preventDefault()});this.initKeys();this.initPointingDevice()};
Controller.prototype.initKeys=function(){var a=this;window.addEventListener("keydown",function(b){b.key?a.keys[b.key]=!0:a.keys["k"+b.keyCode]=!0});window.addEventListener("keyup",function(b){b.key?delete a.keys[b.key]:delete a.keys["k"+b.keyCode]})};
Controller.prototype.initPointingDevice=function(){var a=this,b=document.getElementById("canvas"),c=function(){a.touch=!1;a.point=null};b.addEventListener("mousedown",function(b){a.touch=!0;a.point=FlexibleView.Instance.convert(b.clientX,b.clientY)});b.addEventListener("mousemove",function(b){a.touch&&(a.point=FlexibleView.Instance.convert(b.clientX,b.clientY))});b.addEventListener("mouseup",function(){return c()});b.addEventListener("mouseleave",function(){return c()});b.addEventListener("touchstart",
function(b){var c=b.touches[0];a.touch=!0;a.point=FlexibleView.Instance.convert(c.pageX,c.pageY);b.preventDefault()});b.addEventListener("touchmove",function(b){b=b.touches[0];a.touch=!0;a.point=FlexibleView.Instance.convert(b.pageX,b.pageY)});b.addEventListener("touchend",function(){return c()})};
var EnclosingLine=function(){ActorHandle.call(this,100,100);this.parent=this;this.addHandle(200,100);this.addHandle(200,200);this.addHandle(100,200);this.addHandle(50,150);this.addHandle(50,120);this.spawnList=this.list};$jscomp.inherits(EnclosingLine,ActorHandle);EnclosingLine.prototype.addHandle=function(a,b){a=new ActorHandle(a,b);a.parent=this;this.add(a)};
EnclosingLine.prototype.isHit=function(a,b){var c=this,d=ActorHandle.prototype.isHit.call(this,a,b);this.hit=d;this.lineHit=!1;this.listAll.forEach(function(d){d.isLineHit(a,b)&&(c.lineHit=!0)});return d|this.lineHit};EnclosingLine.prototype.drawLine=function(a){a.lineWidth=.5;a.strokeStyle="lightglay";a.beginPath();a.moveTo(this.x,this.y);this.listAll.forEach(function(b){a.lineTo(b.x,b.y)});a.stroke()};
EnclosingLine.prototype.drawAll=function(a){this.selected?(a.lineWidth=2,a.strokeStyle="navy"):this.lineHit?(a.lineWidth=2,a.strokeStyle="aqua"):a.lineWidth=1;this.listAll.forEach(function(b){b.drawCurve(a)})};EnclosingLine.prototype.draw=function(a){ActorHandle.prototype.draw.call(this,a);a.save();this.drawAll(a);a.restore()};
var Field=function(a,b){this.width=a;this.height=b;this.hW=this.width/2;this.hH=this.height/2;this.scale=4;this.view=new FlexibleView(a,b);this.ty=this.tx=0;this.actorList=[];this.carIx=0;this.carList=[];this.groundList=[];this.focus=null;this.targetList=[];this.dirty=!1;this.setupEvents();Field.Instance=this};
Field.prototype.setupEvents=function(){var a=this,b=this.view.view,c=Controller.Instance.keys;b.addEventListener("mousedown",function(b){b=a.view.convert(b.clientX,b.clientY);b=a.scan(b.x,b.y);c.Control||c.Shift||c.k16||c.k17||(a.targetList=[]);b instanceof ActorHandle&&(a.hold=b)});b.addEventListener("mouseup",function(b){a.dirty=!0;a.hold=null});b.addEventListener("mousemove",function(b){b=a.view.convert(b.clientX,b.clientY);if(a.hold){var c=b.y-a.ty;a.hold.x=b.x-a.tx;a.hold.y=c}else a.scan(b.x,
b.y)})};Field.prototype.addActor=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];var d=this;b.forEach(function(a){d.actorList.push(a);a instanceof Car&&d.carList.push(a);a instanceof Ground&&d.groundList.push(a)});this.dirty=!0};Field.prototype.scan=function(a,b){var c=null,d=a-this.tx,e=b-this.ty;this.actorList.forEach(function(a){a.hit=!1;c||a.isHit(d,e)&&(c=a)});return c};
Field.prototype.clearSelection=function(){this.scan(Number.MAX_VALUE,Number.MAX_VALUE);this.targetList=[]};
Field.prototype.calculatePosition=function(){var a=Controller.Instance.keys;a.PageUp?(this.scale+=.1,8<this.scale&&(this.scale=8)):a.PageDown&&(this.scale-=.1,.4>this.scale&&(this.scale=.4));if(a.c){var b=this.carList.indexOf(this.focus),b=(b+1)%this.carList.length;this.focus=this.carList[b];delete a.c}var c=this.focus,b=.006*Math.PI;if(a.ArrowLeft||a.Left||a.k37)c.radian-=b;else if(a.ArrowRight||a.Right||a.k39)c.radian+=b;if(a.ArrowUp||a.Up||a.k38||a.Control||a.Shift||a.k16||a.k17)c.speed+=10;else if(a.ArrowDown||
a.Down||a.k40)c.speed-=10;this.groundList.forEach(function(a){a.x=c.x;a.y=c.y})};Field.prototype.choiceActor=function(){var a=[];this.actorList.forEach(function(b){b.isGone||(a.push(b),b.spawn.forEach(function(b){a.push(b)}))});a.sort(function(a,c){return a.z-c.z});this.actorList.length!=a.length&&(this.actorList=a,this.dirty=!0)};
Field.prototype.draw=function(){var a=this,b=this.view.ctx,c=this.focus;this.view.clear();this.calculatePosition();this.choiceActor();b.save();b.font="12px 'Times New Roman'";b.textBaseline="middle";b.translate(this.hW,1.5*this.hH);b.scale(this.scale,this.scale);b.rotate(-c.radian-Math.PI/2);b.translate(-c.x,-c.y);this.actorList.forEach(function(c){c.selected=-1!=a.targetList.indexOf(c);c.draw(b)});b.restore()};
var FlexibleView=function(a,b){this.view=document.getElementById("view");this.canvas=document.getElementById("canvas");this.ctx=this.canvas.getContext("2d");this.scale=1;this.init();this.setSize(a,b);FlexibleView.Instance=this};FlexibleView.prototype.setSize=function(a,b){this.width=a;this.height=b;this.canvas.width=a;this.canvas.height=b;this.resize()};
FlexibleView.prototype.init=function(){var a=this,b=document.querySelector('[data-role="header"]'),c=document.querySelector('[data-role="footer"]');this.headerHeight=b?b.offsetHeight:0;this.footerHeight=c?c.offsetHeight:0;this.margin=this.headerHeight+this.footerHeight;window.addEventListener("resize",function(){a.resize()});window.addEventListener("keydown",function(){view.classList.contains("addicting")||view.classList.add("addicting")});window.addEventListener("mousemove",function(){view.classList.remove("addicting")})};
FlexibleView.prototype.resize=function(){var a=document.body.clientWidth/this.width,b=(window.innerHeight-this.margin)/this.height;this.scale=b<a?b:a;this.view.setAttribute("style",["width:"+this.width+"px","height:"+this.height+"px","transform: scale("+this.scale+")"].join(";"))};FlexibleView.prototype.convert=function(a,b){return{x:a/this.scale,y:(b-this.headerHeight)/this.scale}};FlexibleView.prototype.clear=function(){this.ctx.clearRect(0,0,this.width,this.height)};
var Ground=function(){Actor.call(this,0,0,-1);this.createFillStyle("img/ground.1.1.png")};$jscomp.inherits(Ground,Actor);Ground.prototype.createFillStyle=function(a){a=void 0===a?null:a;var b=this,c=FlexibleView.Instance.ctx;this.height=this.width=16;this.fillStyle="rgba(200, 200, 255, 0.7)";this.img=new Image;this.img.onload=function(){b.width=b.img.width;b.height=b.img.height;b.hW=b.width/2;b.hH=b.height/2;b.fillStyle=c.createPattern(b.img,"repeat")};a&&(this.img.src=a)};
Ground.prototype.draw=function(a){var b=3*this.width,c=3*this.height;a.save();a.fillStyle=this.fillStyle;a.fillRect(-this.width,-this.height,b,c);a.restore()};var Tally=function(){};Tally.reset=function(){Tally.val=0};Tally.increment=function(){return++Tally.val};Tally.val=0;var UUID=function(){};UUID.toString=function(){return UUID.Format.replace(/X|Y/g,function(a){var b=16*Math.random()|0;return("X"===a?b:b&3|8).toString(16)})};UUID.Format="XXXXXXXX-XXXX-4XXX-YXXX-XXXXXXXXXXXX";
var Car=function(a,b){Actor.call(this,a,b);this.speed=this.radian=0;this.createFillStyle()};$jscomp.inherits(Car,Actor);
Car.prototype.createFillStyle=function(a){a=void 0===a?null:a;var b=this,c=FlexibleView.Instance.ctx;this.height=this.width=16;this.hW=this.width/2;this.hH=this.height/2;this.fillStyle="rgba(200, 200, 255, 0.7)";this.img=new Image;this.img.onload=function(){b.width=b.img.width;b.height=b.img.height;b.hW=b.width/2;b.hH=b.height/2;b.fillStyle=c.createPattern(b.img,"repeat-x")};a&&(this.img.src=a)};Car.prototype.isHit=function(a,b){return!1};
Car.prototype.calculatePosition=function(){this.x+=Math.cos(this.radian)*this.speed/700;this.y+=Math.sin(this.radian)*this.speed/700;0<Math.abs(this.speed)&&(this.speed+=0<this.speed?-1:1)};Car.prototype.draw=function(a){this.calculatePosition();a.save();a.translate(this.x,this.y);a.rotate(this.radian);a.translate(-this.hW,-this.hH);a.scale(.3,.3);a.fillStyle=this.fillStyle;a.fillRect(0,0,this.width,this.height);a.restore()};var FastCar=function(a,b){Car.call(this,a,b);this.createFillStyle("img/car.fast.png")};
$jscomp.inherits(FastCar,Car);var HeavyCar=function(a,b){Car.call(this,a,b);this.createFillStyle("img/car.heavy.png")};$jscomp.inherits(HeavyCar,Car);var OrdinaryCar=function(a,b){Car.call(this,a,b);this.createFillStyle("img/car.ordinary.png")};$jscomp.inherits(OrdinaryCar,Car);document.addEventListener("DOMContentLoaded",function(){new AppMain});var AppMain=function(){console.log("AppMain")};
